export const allActivities = [
  "ski",
  "trekking",
  "rock climbing",
  "alpine",
  "mountain",
];

export const mockUser = {
  id: 1,
  phone: "+1 (680) 787-0548",
  email: "melvin.bruen@example.net",
  img: "https://d1ldvf68ux039x.cloudfront.net/thumbs/photos/1306/952634/1000w_q95.jpg",
  img_cover:
    "https://img.freepik.com/free-photo/snowy-mountain-lake-beautiful-landscape_181624-20829.jpg?w=2000",
  email_verified_at: "2023-01-28T14:03:42.000000Z",
  facebook:
    "https://waelchi.com/qui-illum-assumenda-voluptate-explicabo-possimus-qui.html",
  whatsapp: "http://www.willms.net",
  youtube: "http://www.howe.com/",
  instagram: "http://spinka.com/",
  language: "Geo / Eng / Rus",
  activities: ["SKI", "ROCK CLIMBING", "MOUNTAIN"],
  sort: 87,
  condition: "Archived",
  created_at: "2023-01-28T14:03:42.000000Z",
  updated_at: "2023-01-28T14:03:42.000000Z",
  trans: {
    id: 1,
    user_id: 1,
    locale: "en",
    name: "Florida",
    surname: "Adelbert",
    title: "Total background projection",
    description:
      "industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentitype specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially emaining essentially emaining essentially unchanged.It has survived not only five centuries, but also the leap into electronic typesetting, remaining unchanged",
    description_min:
      "Debitis fugit et in ratione. Fugit quos itaque quasi molestiae reiciendis ullam cupiditate. Vel aperiam suscipit omnis libero dolorem sapiente consequatur. Sequi blanditiis autem nisi.",
    keywords: "Odio, et, suscipit, asperiores, et, nostrum, similique.",
    url: "http://conroy.com/unde-et-et-quibusdam-quo.html",
    created_at: "2023-01-28T14:03:42.000000Z",
    updated_at: "2023-01-28T14:03:42.000000Z",
  },
  gallery: [
    {
      id: 1,
      user_id: 1,
      img: "3.png",
      title: "Future-proofed regional budgetarymanagement",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
    },
    {
      id: 2,
      user_id: 1,
      img: "2.png",
      title: "Robust high-level concept",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
    },
    {
      id: 3,
      user_id: 1,
      img: "3.png",
      title: "Open-architected real-time model",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
    },
  ],
  posts: [
    {
      id: 1,
      user_id: 1,
      img: "2-post.png",
      img_cover: "3-post.png",
      img_splash: "3-post.png",
      video: null,
      title: "Voluptatem facilis deleniti et.",
      description:
        "Cupiditate voluptatem et ut est alias facilis mollitia magni ad perspiciatis magnam eos est porro porro et voluptatem numquam rerum modi quas autem voluptas quo perferendis harum veritatis sequi perferendis incidunt et ducimus saepe quibusdam unde doloribus nobis beatae non unde optio eum consequatur repellendus labore et quia saepe at sint ad non veniam est et laudantium rerum ducimus nulla voluptatem autem officia ut modi iure nihil quia officiis error facere labore ipsum nemo quasi ullam neque voluptatem doloribus aliquam temporibus commodi et aliquam ut et facilis sunt iure debitis quo enim molestias ex possimus et qui eaque tempore deleniti.",
      description_min:
        "Repellat nesciunt sint qui praesentium assumenda et itaque voluptatem eius corrupti omnis quo atque cumque aut deserunt praesentium et ab ratione dolor atque iusto nemo ipsa maxime accusantium molestiae fugiat rerum est dolor voluptatibus ducimus repellat praesentium qui et aut molestiae adipisci vel optio quaerat aut sunt voluptas nam quia tenetur et omnis rem ullam delectus aut id ab reprehenderit et laborum earum cumque est eos molestiae et unde hic voluptatibus corporis ut illo qui itaque nulla officia ipsum quo voluptates at neque facere perferendis voluptatem ut inventore est culpa aspernatur quia non totam iste pariatur eos quaerat voluptatum consequatur accusamus magni repellendus sit necessitatibus explicabo id ab ex rerum repellendus minima laborum est et molestiae omnis culpa ipsam dolorum ipsam minima quaerat sit dolorem quia eum molestiae et aliquam aut aspernatur sed nihil ea velit commodi aliquam similique enim expedita aliquam laboriosam voluptas nostrum et cumque qui.",
      keywords: "Unde dolor dolor autem.",
      url: "http://grimes.com/harum-est-ducimus-saepe-fuga.html",
      sort: 95,
      highlight: "Normal",
      status: "Archived",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
    },
    {
      id: 2,
      user_id: 1,
      img: "2-post.png",
      img_cover: "3-post.png",
      img_splash: "3-post.png",
      video: null,
      title: "Explicabo et.",
      description:
        "Ea non id optio eum quo sunt minima voluptatem iure doloremque voluptatem natus sit eos quod earum iure quia sit qui quia doloribus qui reiciendis voluptas sit et rerum rem atque qui voluptatibus esse quam qui dolor amet deserunt incidunt nesciunt architecto et ab beatae nihil accusamus illum sit quisquam minima est a ut quia a earum quod eos quis ipsa provident et illum aliquid adipisci inventore officia sit quia corrupti beatae vero ad maiores libero et rem aut soluta aut dolorem aut neque nisi sapiente at sit perferendis facere quaerat expedita ea quibusdam rerum voluptatem optio excepturi et unde.",
      description_min:
        "Et et cupiditate doloribus eum quis dolorem qui molestiae ut id rerum hic excepturi nihil quo reprehenderit consequuntur velit dolorem omnis et quo explicabo distinctio veritatis accusamus possimus itaque et mollitia sed vel in est asperiores in et unde ad iure dolores id numquam consectetur ut quibusdam pariatur magnam velit accusantium sed ipsam rerum voluptate repudiandae optio alias aut sequi cupiditate sed et unde quaerat rem non aut est ad asperiores magni a eos dicta aut eos iure non provident dolorem rerum fugiat quidem accusantium est tenetur id distinctio eos et beatae incidunt consequatur quibusdam sed eum vitae expedita sapiente a occaecati aliquid ut et dicta dicta architecto distinctio assumenda illum magnam voluptas illo voluptates alias laboriosam quia sunt enim aut molestiae possimus magni reprehenderit explicabo quam aliquam in itaque nostrum deserunt vel id quia molestias ut voluptatem sit ex quis natus quo qui veniam illum unde nemo minima fugit natus aut modi fuga veniam soluta cumque voluptatibus adipisci assumenda ut nihil in magni perferendis et odio aut odit ipsum consequuntur enim sit molestiae voluptas qui delectus natus eaque dolor voluptates minus sint praesentium porro quibusdam unde minima ut ut a magnam aliquid illo ut excepturi deserunt ut illum voluptas aperiam provident et nobis quaerat distinctio voluptates incidunt officiis et harum et dolorem animi vitae dignissimos exercitationem et eum sit hic omnis reiciendis rerum voluptas.",
      keywords: "Totam officiis rerum.",
      url: "https://rempel.net/odit-consequuntur-ratione-dignissimos-totam-numquam.html",
      sort: 93,
      highlight: "Recent",
      status: "Draft",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
    },
  ],
  tegs: [
    {
      id: 1,
      img: "1-teg.png",
      video: null,
      sort: 48,
      status: "Published",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
      pivot: {
        user_id: 1,
        teg_id: 1,
      },
      trans: {
        id: 1,
        teg_id: 1,
        locale: "en",
        title: "Praesentium nisi dolorem.",
        description:
          "Quam ducimus beatae qui ut autem rerum commodi in earum itaque quo veniam eum voluptate officiis error at aspernatur quaerat sint et ullam nihil est velit labore dolores exercitationem quos sit et dolorem ut voluptatem nihil dolores cupiditate ut magnam magnam aut illum laboriosam molestias molestias debitis omnis sint unde ab et sequi laboriosam ea sit perferendis explicabo debitis expedita qui neque doloremque dolorum adipisci temporibus ipsum dolorem iusto similique tempore maxime necessitatibus sed consequatur nulla recusandae ipsa veritatis ipsum aut magnam tenetur est facere nihil rerum a fuga repellat distinctio deserunt omnis porro quos qui eum.",
        description_min: "Nihil perspiciatis.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
    },
    {
      id: 2,
      img: "1-teg.png",
      video: null,
      sort: 25,
      status: "Archived",
      created_at: "2023-01-28T14:03:42.000000Z",
      updated_at: "2023-01-28T14:03:42.000000Z",
      pivot: {
        user_id: 1,
        teg_id: 2,
      },
      trans: {
        id: 4,
        teg_id: 2,
        locale: "en",
        title: "Distinctio illo.",
        description:
          "Consequatur quisquam consequuntur placeat dolor laboriosam nesciunt quasi laboriosam fugiat voluptatem vel recusandae omnis impedit voluptatem aut dolorum dolorum est sint inventore sed unde et voluptatum voluptate quisquam tenetur eveniet accusamus dicta sunt quia reiciendis facilis repellat odio ea sed nihil qui omnis nemo ipsam aut officiis qui quod debitis asperiores odit et sunt at ex suscipit et numquam cupiditate ullam iusto itaque nihil tenetur ut nostrum fugit eos facere at sint laboriosam quis omnis rerum doloribus aut omnis quidem consectetur voluptatem recusandae sunt vel sed et corporis possimus iusto pariatur quia temporibus provident sint tempore aperiam vel autem enim ad facere qui eos quia dolorem aut nemo quia explicabo dolores eius reiciendis est consequatur dolore deleniti consectetur voluptatem autem architecto quo aliquid quis iusto aut iste molestiae commodi dolores commodi et similique repudiandae voluptatem est tempore eos ullam deleniti ut commodi libero cupiditate laudantium quia nam excepturi voluptatibus explicabo quam saepe at molestiae nihil ipsum omnis et et repellendus velit qui non deserunt est et qui nam unde occaecati vitae harum voluptatem minus exercitationem qui a voluptate voluptatem a odio molestias fugiat omnis occaecati reprehenderit accusantium mollitia veniam qui cum ipsam earum deserunt quis consequatur laborum inventore harum aut impedit perferendis tempora ipsum.",
        description_min: "Amet nobis.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
    },
  ],
};

export const mockPosts = [
  {
    id: 1,
    user_id: 1,
    img: "https://res.cloudinary.com/do8a4tbyb/image/upload/v1666925744/aboutPage/landingPageMain_frqghx.png",
    name: "Giorgi",
    surname: "Tsibakhashvili",
    img_cover: "3-post.png",
    img_splash: "3-post.png",
    video: null,
    title: "Voluptatem facilis deleniti et.",
    description:
      "Cupiditate voluptatem et ut est alias facilis mollitia magni ad perspiciatis magnam eos est porro porro et voluptatem numquam rerum modi quas autem voluptas quo perferendis harum veritatis sequi perferendis incidunt et ducimus saepe quibusdam unde doloribus nobis beatae non unde optio eum consequatur repellendus labore et quia saepe at sint ad non veniam est et laudantium rerum ducimus nulla voluptatem autem officia ut modi iure nihil quia officiis error facere labore ipsum nemo quasi ullam neque voluptatem doloribus aliquam temporibus commodi et aliquam ut et facilis sunt iure debitis quo enim molestias ex possimus et qui eaque tempore deleniti.",
    description_min:
      "Repellat nesciunt sint qui praesentium assumenda et itaque voluptatem eius corrupti omnis quo atque cumque aut deserunt praesentium et ab ratione dolor atque iusto nemo ipsa maxime accusantium molestiae fugiat rerum est dolor voluptatibus ducimus repellat praesentium qui et aut molestiae adipisci vel optio quaerat aut sunt voluptas nam quia tenetur et omnis rem ullam delectus aut id ab reprehenderit et laborum earum cumque est eos molestiae et unde hic voluptatibus corporis ut illo qui itaque nulla officia ipsum quo voluptates at neque facere perferendis voluptatem ut inventore est culpa aspernatur quia non totam iste pariatur eos quaerat voluptatum consequatur accusamus magni repellendus sit necessitatibus explicabo id ab ex rerum repellendus minima laborum est et molestiae omnis culpa ipsam dolorum ipsam minima quaerat sit dolorem quia eum molestiae et aliquam aut aspernatur sed nihil ea velit commodi aliquam similique enim expedita aliquam laboriosam voluptas nostrum et cumque qui.",
    keywords: "Unde dolor dolor autem.",
    url: "http://grimes.com/harum-est-ducimus-saepe-fuga.html",
    sort: 95,
    highlight: "Normal",
    status: "Published",
    created_at: "2023-01-28T14:03:42.000000Z",
    updated_at: "2023-01-28T14:03:42.000000Z",
    comments_count: 2,
    likers_ids: [1, 38478, 23847, 3487, 1238],
    gallery: [
      {
        id: 1,
        post_id: 1,
        img: "https://media.newyorker.com/photos/5e506688b9920c00082c1417/master/w_2560%2Cc_limit/200302_r35897.jpg",
        title: "Quam sequi vel.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
      {
        id: 2,
        post_id: 1,
        img: "https://media.istockphoto.com/id/175515475/photo/mountains.jpg?s=612x612&w=0&k=20&c=e0TxdqpmQxgSYoHiB6F6x-SLsLbIeW7yM3weSBNyZ5U=",
        title: "Aut consequatur repudiandae.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
      {
        id: 3,
        post_id: 1,
        img: "https://res.cloudinary.com/dpj4hptgm/image/upload/v1671895744/about-gmga/shutterstock_700116601_di7gmw.png",
        title: "Accusamus veniam et.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
    ],
    comments: [
      {
        id: 1129,
        user_id: 8,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Ana",
        surname: "Khizanishvili",
        post_id: 1,
        reply_id: 4,
        comment: "Voluptas debitis sed delectus.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [38478, 23847, 3487, 1238],
        children: [],
      },
      {
        id: 1249,
        user_id: 8,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Lasha",
        surname: "Giorgadze",
        post_id: 1,
        reply_id: 4,
        comment:
          "Debitis sed delectus debitis sed delectus Voluptas debitis sed delectus.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [1, 38478, 23847],
        children: [],
      },
    ],
  },
  {
    id: 2,
    user_id: 1,
    img: "https://res.cloudinary.com/do8a4tbyb/image/upload/v1666925744/aboutPage/landingPageMain_frqghx.png",
    name: "Giorgi",
    surname: "Tsibakhashvili",
    img_cover: "3-post.png",
    img_splash: "3-post.png",
    video: null,
    title: "Explicabo et.",
    description:
      "Ea non id optio eum quo sunt minima voluptatem iure doloremque voluptatem natus sit eos quod earum iure quia sit qui quia doloribus qui reiciendis voluptas sit et rerum rem atque qui voluptatibus esse quam qui dolor amet deserunt incidunt nesciunt architecto et ab beatae nihil accusamus illum sit quisquam minima est a ut quia a earum quod eos quis ipsa provident et illum aliquid adipisci inventore officia sit quia corrupti beatae vero ad maiores libero et rem aut soluta aut dolorem aut neque nisi sapiente at sit perferendis facere quaerat expedita ea quibusdam rerum voluptatem optio excepturi et unde.",
    description_min:
      "Et et cupiditate doloribus eum quis dolorem qui molestiae ut id rerum hic excepturi nihil quo reprehenderit consequuntur velit dolorem omnis et quo explicabo distinctio veritatis accusamus possimus itaque et mollitia sed vel in est asperiores in et unde ad iure dolores id numquam consectetur ut quibusdam pariatur magnam velit accusantium sed ipsam rerum voluptate repudiandae optio alias aut sequi cupiditate sed et unde quaerat rem non aut est ad asperiores magni a eos dicta aut eos iure non provident dolorem rerum fugiat quidem accusantium est tenetur id distinctio eos et beatae incidunt consequatur quibusdam sed eum vitae expedita sapiente a occaecati aliquid ut et dicta dicta architecto distinctio assumenda illum magnam voluptas illo voluptates alias laboriosam quia sunt enim aut molestiae possimus magni reprehenderit explicabo quam aliquam in itaque nostrum deserunt vel id quia molestias ut voluptatem sit ex quis natus quo qui veniam illum unde nemo minima fugit natus aut modi fuga veniam soluta cumque voluptatibus adipisci assumenda ut nihil in magni perferendis et odio aut odit ipsum consequuntur enim sit molestiae voluptas qui delectus natus eaque dolor voluptates minus sint praesentium porro quibusdam unde minima ut ut a magnam aliquid illo ut excepturi deserunt ut illum voluptas aperiam provident et nobis quaerat distinctio voluptates incidunt officiis et harum et dolorem animi vitae dignissimos exercitationem et eum sit hic omnis reiciendis rerum voluptas.",
    keywords: "Totam officiis rerum.",
    url: "https://rempel.net/odit-consequuntur-ratione-dignissimos-totam-numquam.html",
    sort: 93,
    highlight: "Recent",
    status: "Published",
    created_at: "2023-01-28T14:03:42.000000Z",
    updated_at: "2023-01-28T14:03:42.000000Z",
    comments_count: 16,
    likers_ids: [
      38478, 23847, 3487, 1238, 38247, 324879, 12837, 1232, 9348, 91823, 12938,
      49537,
    ],
    gallery: [
      {
        id: 4,
        post_id: 2,
        img: "https://expeditioncolombia.com/wp-content/uploads/elementor/thumbs/jungle-trek-4-oypnsoxdd4zcys3prmv5708s46ppf77n0gapmaou3c.jpg",
        title: "Occaecati et ipsum et.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
      {
        id: 5,
        post_id: 2,
        img: "https://static.wixstatic.com/media/28dab9_eb070bce373a415f8b230385a0d13c43~mv2.jpg/v1/crop/x_0,y_11,w_1920,h_1259/fill/w_640,h_382,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/hiking%20trekking%20tours%20georgia%20caucasus_j.jpg",
        title: "Qui omnis maiores rerum.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
      },
    ],
    comments: [
      {
        id: 5213,
        user_id: 1,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Ana",
        surname: "Khizanishvili",
        post_id: 2,
        reply_id: 7,
        comment: "Tenetur sunt possimus.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [38478, 1, 23847],
        children: [
          {
            id: 4351,
            user_id: 8,
            img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
            name: "Ana",
            surname: "Khizanishvili",
            post_id: 3,
            reply_id: 5,
            comment: "Saepe dolorem rerum.",
            created_at: "2023-01-28T14:03:42.000000Z",
            updated_at: "2023-01-28T14:03:42.000000Z",
            parent_comment_id: 5213,
            likers_ids: [38478, 23847],
            children: [
              {
                id: 13434,
                user_id: 1,
                img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
                name: "Ana",
                surname: "Khizanishvili",
                post_id: 13,
                reply_id: 1,
                comment: "Eligendi possimus quas accusantium molestiae.",
                created_at: "2023-01-28T14:03:42.000000Z",
                updated_at: "2023-01-28T14:03:42.000000Z",
                parent_comment_id: 4351,
                likers_ids: [1, 23, 4543],
                children: [],
              },
            ],
          },
          {
            id: 22348,
            user_id: 4,
            img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
            name: "Ana",
            surname: "Khizanishvili",
            post_id: 16,
            reply_id: 5,
            comment: "A fugiat eum molestiae possimus.",
            created_at: "2023-01-28T14:03:42.000000Z",
            updated_at: "2023-01-28T14:03:42.000000Z",
            parent_comment_id: 5213,
            likers_ids: [23847, 123, 38478, 23847],
            children: [],
          },
        ],
      },
      {
        id: 732467,
        user_id: 9,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Ana",
        surname: "Khizanishvili",
        post_id: 2,
        reply_id: 9,
        comment: "Doloremque quasi est ex labore.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [2347, 23847, 123, 38478, 23847],
        children: [
          {
            id: 8795,
            user_id: 1,
            img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
            name: "Ana",
            surname: "Khizanishvili",
            post_id: 2,
            reply_id: 7,
            comment: "Tenetur sunt possimus.",
            created_at: "2023-01-28T14:03:42.000000Z",
            updated_at: "2023-01-28T14:03:42.000000Z",
            parent_comment_id: 732467,
            likers_ids: [1],
            children: [
              {
                id: 4561,
                user_id: 8,
                img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
                name: "Ana",
                surname: "Khizanishvili",
                post_id: 3,
                reply_id: 5,
                comment: "Saepe dolorem rerum.",
                created_at: "2023-01-28T14:03:42.000000Z",
                updated_at: "2023-01-28T14:03:42.000000Z",
                parent_comment_id: 8795,
                likers_ids: [2347, 23847, 123, 38478, 23847],
                children: [
                  {
                    id: 89714,
                    user_id: 1,
                    img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
                    name: "Ana",
                    surname: "Khizanishvili",
                    post_id: 13,
                    reply_id: 1,
                    comment: "Eligendi possimus quas accusantium molestiae.",
                    created_at: "2023-01-28T14:03:42.000000Z",
                    updated_at: "2023-01-28T14:03:42.000000Z",
                    parent_comment_id: 4561,
                    likers_ids: [1342, 23, 23847],
                    children: [],
                  },
                ],
              },
              {
                id: 281237,
                user_id: 4,
                img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
                name: "Ana",
                surname: "Khizanishvili",
                post_id: 16,
                reply_id: 5,
                comment: "A fugiat eum molestiae possimus.",
                created_at: "2023-01-28T14:03:42.000000Z",
                updated_at: "2023-01-28T14:03:42.000000Z",
                parent_comment_id: 8795,
                likers_ids: [23847],
                children: [],
              },
            ],
          },
          {
            id: 14561,
            user_id: 3,
            img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
            name: "Ana",
            surname: "Khizanishvili",
            post_id: 2,
            reply_id: 7,
            comment: "Sunt doloribus odit repellendus nihil dicta.",
            created_at: "2023-01-28T14:03:42.000000Z",
            updated_at: "2023-01-28T14:03:42.000000Z",
            parent_comment_id: 732467,
            likers_ids: [
              23, 4543, 47358, 234738, 328472, 7548, 374, 3289, 2347, 23847,
              123, 38478, 23847,
            ],
            children: [
              {
                id: 4716,
                user_id: 4,
                img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
                name: "Ana",
                surname: "Khizanishvili",
                post_id: 2,
                reply_id: 11,
                comment: "Eligendi qui sit.",
                created_at: "2023-01-28T14:03:42.000000Z",
                updated_at: "2023-01-28T14:03:42.000000Z",
                parent_comment_id: 14561,
                likers_ids: [],
                children: [],
              },
            ],
          },
          {
            id: 22456,
            user_id: 1,
            img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
            name: "Ana",
            surname: "Khizanishvili",
            post_id: 13,
            reply_id: 7,
            comment: "Vitae aut deserunt enim.",
            created_at: "2023-01-28T14:03:42.000000Z",
            updated_at: "2023-01-28T14:03:42.000000Z",
            parent_comment_id: 732467,
            likers_ids: [],
            children: [],
          },
        ],
      },
      {
        id: 19801,
        user_id: 3,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Ana",
        surname: "Khizanishvili",
        post_id: 2,
        reply_id: 7,
        comment: "Sunt doloribus odit repellendus nihil dicta.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [],
        children: [
          {
            id: 13456,
            user_id: 4,
            img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
            name: "Ana",
            surname: "Khizanishvili",
            post_id: 2,
            reply_id: 11,
            comment: "Eligendi qui sit.",
            created_at: "2023-01-28T14:03:42.000000Z",
            updated_at: "2023-01-28T14:03:42.000000Z",
            parent_comment_id: 19801,
            likers_ids: [],
            children: [],
          },
        ],
      },
      {
        id: 12342,
        user_id: 5,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Ana",
        surname: "Khizanishvili",
        post_id: 2,
        reply_id: 10,
        comment: "Quod ut dignissimos.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [1, 23, 4543, 47358, 234738, 328472, 7548],
        children: [],
      },
      {
        id: 167564,
        user_id: 4,
        img: "https://www.westend61.de/images/0001051300pw/rock-climber-rock-climbing-looking-at-camera-smiling-red-rock-las-vegas-nevada-united-states-ISF19872.jpg",
        name: "Ana",
        surname: "Khizanishvili",
        post_id: 2,
        reply_id: 11,
        comment: "Eligendi qui sit.",
        created_at: "2023-01-28T14:03:42.000000Z",
        updated_at: "2023-01-28T14:03:42.000000Z",
        parent_comment_id: null,
        likers_ids: [],
        children: [],
      },
    ],
  },
];

export const likers = [
  {
    name: "Ana",
    surname: "Khizanishvili",
    id: 2131,
  },
  {
    name: "Nana",
    surname: "Modebadze",
    id: 8472,
  },
  {
    name: "Giorgi",
    surname: "Giorgadze",
    id: 9414,
  },
  {
    name: "Bero",
    surname: "Beria",
    id: 2742,
  },
  {
    name: "George",
    surname: "Kiladze",
    id: 843472,
  },
  {
    name: "Dati",
    surname: "Giorgadze",
    id: 941344,
  },
  {
    name: "Lasha",
    surname: "Beria",
    id: 274232,
  },
];
